version "4.7.1"

#include "ZAlice/tom_main.zs"
#include "ZAlice/tom_events.zs"
#include "ZAlice/tom_items.zs"
#include "ZAlice/tom_constants.zs"
#include "ZAlice/tom_player.zs"
#include "ZAlice/tom_weapon.zs"
#include "ZAlice/w_knife.zs"
#include "ZAlice/w_cards.zs"
#include "ZAlice/w_teapot.zs"
#include "ZAlice/w_eyestaff.zs"

#include "ZAlice/GZBeam/laser_math.zsc"
#include "ZAlice/GZBeam/laser_base.zsc"